name: Release
env:
  PLUGIN_NAME: ${{ github.event.repository.name }}
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: latest

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build dist
        run: pnpm prod

      - name: Install zip
        uses: montudor/action-zip@v1

